version: '3.8'

services:
  pdf-rag:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CHROMA_SERVER_HOST=${CHROMA_SERVER_HOST:-api.trychroma.com}
      - CHROMA_SERVER_PORT=${CHROMA_SERVER_PORT:-443}
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./medical_chroma_db:/app/medical_chroma_db
    restart: unless-stopped
