services:
  - type: web
    name: pdf-rag-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false  # Set this in Render dashboard
      - key: PYTHONPATH
        value: .
